Repository depromeet/layer-server, pull requests merged in 2024-07, with the labels that each got.

#4 [feat/#3] PR 테스트
  README.md
Labels: 📖 documentation

#6 [Chore/1] 깃허브 액션을 통한 CI/CD 구축
  .github/workflows/ci-cd-compose.yaml
  .github/workflows/ci-cd.yaml
  build.gradle
  layer-api/Dockerfile
  layer-api/build.gradle
  layer-api/infra/development/docker-compose.yaml
  layer-api/infra/development/nginx.conf
  layer-api/infra/production/docker-compose.yaml
  layer-api/infra/production/nginx.conf
  layer-api/k8s/development/deployment.yaml
  layer-api/src/main/java/org/layer/api/LayerApplication.java
  layer-api/src/main/java/org/layer/api/controller/HelloController.java
  layer-common/build.gradle
  layer-common/src/main/java/org/layer/Main.java
  layer-common/src/main/java/org/layer/common/model/Sample.java
  layer-domain/build.gradle
  layer-external/build.gradle
Labels: 🚀 feature

#2 [Feature/1] Spring Security JWT 인증
  .gitignore
  layer-api/build.gradle
  layer-api/src/main/java/org/layer/auth/api/AuthController.java
  layer-api/src/main/java/org/layer/auth/exception/TokenException.java
  layer-api/src/main/java/org/layer/auth/jwt/JwtAuthenticationFilter.java
  layer-api/src/main/java/org/layer/auth/jwt/JwtProvider.java
  layer-api/src/main/java/org/layer/auth/jwt/JwtToken.java
  layer-api/src/main/java/org/layer/auth/jwt/JwtValidationType.java
  layer-api/src/main/java/org/layer/auth/jwt/JwtValidator.java
  layer-api/src/main/java/org/layer/auth/jwt/MemberAuthentication.java
  layer-api/src/main/java/org/layer/auth/jwt/RefreshToken.java
  layer-api/src/main/java/org/layer/auth/jwt/SecretKeyFactory.java
  layer-api/src/main/java/org/layer/auth/service/JwtService.java
  layer-api/src/main/java/org/layer/config/AuthValueConfig.java
  layer-api/src/main/java/org/layer/config/RedisConfig.java
  layer-api/src/main/java/org/layer/config/SecurityConfig.java
  layer-api/src/main/java/org/layer/member/Member.java
  layer-api/src/main/java/org/layer/member/MemberRole.java
  layer-api/src/main/resources/application.yml
Labels: 🚀 feature

#14 feat: 엔티티 및 예외 클래스 생성
  build.gradle
  layer-api/src/main/java/org/layer/common/exception/ExceptionResponse.java
  layer-api/src/main/java/org/layer/common/exception/GlobalExceptionHandler.java
  layer-api/src/main/java/org/layer/member/Member.java
  layer-common/src/main/java/org/layer/common/exception/BaseCustomException.java
  layer-common/src/main/java/org/layer/common/exception/ExceptionType.java
  layer-common/src/main/java/org/layer/common/exception/MemberExceptionType.java
  layer-common/src/main/java/org/layer/common/model/Sample.java
  layer-domain/src/main/java/org/layer/Main.java
  layer-domain/src/main/java/org/layer/domain/answer/entity/Answer.java
  layer-domain/src/main/java/org/layer/domain/answer/repository/AnswerRepository.java
  layer-domain/src/main/java/org/layer/domain/form/entity/Form.java
  layer-domain/src/main/java/org/layer/domain/form/repository/FormRepository.java
  layer-domain/src/main/java/org/layer/domain/member/entity/Member.java
  layer-domain/src/main/java/org/layer/domain/member/entity/MemberRole.java
  layer-domain/src/main/java/org/layer/domain/member/entity/SocialType.java
  layer-domain/src/main/java/org/layer/domain/member/repository/MemberRepository.java
  layer-domain/src/main/java/org/layer/domain/question/entity/Question.java
  layer-domain/src/main/java/org/layer/domain/question/entity/QuestionType.java
  layer-domain/src/main/java/org/layer/domain/question/repository/QuestionRepository.java
  layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
  layer-domain/src/main/java/org/layer/domain/retrospect/entity/RetrospectStatus.java
  layer-domain/src/main/java/org/layer/domain/retrospect/repository/RetrospectRepository.java
  layer-domain/src/main/java/org/layer/domain/space/entity/Field.java
  layer-domain/src/main/java/org/layer/domain/space/entity/MemberSpaceRelation.java
  layer-domain/src/main/java/org/layer/domain/space/entity/Space.java
  layer-domain/src/main/java/org/layer/domain/space/entity/SpaceCategory.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepository.java
  layer-domain/src/main/java/org/layer/domain/template/entity/dummy.txt
  layer-domain/src/main/java/org/layer/domain/template/repository/dummy.txt
Labels: 🚀 feature, 📚 setting

#15 fix: 컴파일 에러 수정
  .gitignore
  build.gradle
  layer-api/src/main/java/org/layer/api/controller/HelloController.java
  layer-api/src/main/java/org/layer/auth/api/AuthController.java
  layer-api/src/main/java/org/layer/auth/jwt/JwtAuthenticationFilter.java
  layer-api/src/main/java/org/layer/auth/jwt/MemberAuthentication.java
  layer-api/src/main/java/org/layer/auth/service/JwtService.java
  layer-api/src/main/java/org/layer/config/RedisConfig.java
Labels: 🐞bug

#18 fix/LS-14 Member 엔티티 수정
  layer-domain/src/main/java/org/layer/domain/member/entity/Member.java
Labels: 🛠️ enhancement

#19 feat/LS-15, LS-16: 회고폼 생성 API 구현
  build.gradle
  layer-api/src/main/java/org/layer/LayerApplication.java
  layer-api/src/main/java/org/layer/retrospect/controller/RetrospectApi.java
  layer-api/src/main/java/org/layer/retrospect/controller/RetrospectController.java
  layer-api/src/main/java/org/layer/retrospect/controller/dto/request/RetrospectCreateRequest.java
  layer-api/src/main/java/org/layer/retrospect/service/RetrospectService.java
  layer-api/src/main/java/org/layer/retrospect/service/dto/RetrospectCreateServiceRequest.java
  layer-domain/src/main/java/org/layer/domain/common/BaseTimeEntity.java
  layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
  layer-external/src/main/java/org/layer/Main.java
  layer-external/src/main/java/org/layer/external/dummy.txt
Labels: 📖 documentation, 📚 setting

#23 refactor/LS-17: 인증 관련 코드 리뷰 반영, 리팩토링, 탈퇴 구현, Swagger 작업
  build.gradle
  layer-api/src/main/java/org/layer/config/RedisConfig.java
  layer-api/src/main/java/org/layer/domain/auth/controller/AuthApi.java
  layer-api/src/main/java/org/layer/domain/auth/controller/AuthController.java
  layer-api/src/main/java/org/layer/domain/auth/controller/dto/ReissueTokenRequest.java
  layer-api/src/main/java/org/layer/domain/auth/controller/dto/SignOutRequest.java
  layer-api/src/main/java/org/layer/domain/auth/controller/dto/WithdrawMemberRequest.java
  layer-api/src/main/java/org/layer/domain/auth/service/AuthService.java
  layer-api/src/main/java/org/layer/domain/jwt/JwtAuthenticationFilter.java
  layer-api/src/main/java/org/layer/domain/jwt/JwtValidator.java
  layer-api/src/main/java/org/layer/domain/jwt/service/JwtService.java
  layer-api/src/main/java/org/layer/domain/member/service/MemberService.java
  layer-api/src/main/java/org/layer/domain/member/service/MemberUtil.java
  layer-common/build.gradle
  layer-common/src/main/java/org/layer/common/exception/MemberExceptionType.java
  layer-external/build.gradle
  layer-external/src/main/java/org/layer/oauth/dto/service/google/GoogleGetMemberInfoServiceResponse.java
  layer-external/src/main/java/org/layer/oauth/service/GoogleService.java
  layer-external/src/main/java/org/layer/oauth/service/KakaoService.java
  layer-external/src/main/java/org/layer/oauth/service/OAuthService.java
Labels: 📖 documentation, 🛠️ enhancement, 🚀 feature

#24 feat/LS-13: 스페이스 API 구현
  build.gradle
  layer-api/src/main/java/org/layer/config/SecurityConfig.java
  layer-api/src/main/java/org/layer/config/SwaggerConfig.java
  layer-api/src/main/java/org/layer/domain/auth/controller/AuthController.java
  layer-api/src/main/java/org/layer/domain/retrospect/controller/RetrospectApi.java
  layer-api/src/main/java/org/layer/domain/retrospect/controller/RetrospectController.java
  layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/request/RetrospectCreateRequest.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/dto/RetrospectCreateServiceRequest.java
  layer-api/src/main/java/org/layer/domain/space/api/SpaceApi.java
  layer-api/src/main/java/org/layer/domain/space/controller/SpaceController.java
  layer-api/src/main/java/org/layer/domain/space/dto/SpaceRequest.java
  layer-api/src/main/java/org/layer/domain/space/dto/SpaceResponse.java
  layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
  layer-api/src/main/java/org/layer/resolver/MemberIdResolver.java
  layer-api/src/main/java/org/layer/retrospect/controller/RetrospectController.java
  layer-common/src/main/java/org/layer/common/annotation/DisableSwaggerSecurity.java
  layer-common/src/main/java/org/layer/common/annotation/MemberId.java
  layer-common/src/main/java/org/layer/common/dto/Meta.java
  layer-common/src/main/java/org/layer/common/exception/ExceptionResponse.java
  layer-common/src/main/java/org/layer/common/exception/GlobalExceptionHandler.java
  layer-domain/src/main/java/org/layer/domain/BaseEntity.java
  layer-domain/src/main/java/org/layer/domain/block/converter/BlockStyleConverter.java
  layer-domain/src/main/java/org/layer/domain/block/entity/Block.java
  layer-domain/src/main/java/org/layer/domain/block/enums/BlockType.java
  layer-domain/src/main/java/org/layer/domain/question/converter/QuestionTypeConverter.java
  layer-domain/src/main/java/org/layer/domain/question/entity/Question.java
  layer-domain/src/main/java/org/layer/domain/question/entity/QuestionType.java
  layer-domain/src/main/java/org/layer/domain/questionOption/entity/QuestionOption.java
  layer-domain/src/main/java/org/layer/domain/space/dto/SpaceWithMemberCount.java
  layer-domain/src/main/java/org/layer/domain/space/entity/MemberSpaceRelation.java
  layer-domain/src/main/java/org/layer/domain/space/entity/Space.java
  layer-domain/src/main/java/org/layer/domain/space/entity/SpaceField.java
  layer-domain/src/main/java/org/layer/domain/space/repository/MemberSpaceRelationRepository.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepository.java
Labels: 🛠️ enhancement

#25 feat: 스페이스 단건조회 / LS-13 리뷰 사항 적용
  build.gradle
  layer-api/src/main/java/org/layer/config/AuthValueConfig.java
  layer-api/src/main/java/org/layer/config/SwaggerConfig.java
  layer-api/src/main/java/org/layer/domain/jwt/JwtAuthenticationFilter.java
  layer-api/src/main/java/org/layer/domain/space/api/SpaceApi.java
  layer-api/src/main/java/org/layer/domain/space/controller/SpaceController.java
  layer-api/src/main/java/org/layer/domain/space/dto/SpaceRequest.java
  layer-api/src/main/java/org/layer/domain/space/exception/SpaceExceptionType.java
  layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
  layer-common/src/main/java/org/layer/common/annotation/AtLeastNotNull.java
  layer-common/src/main/java/org/layer/common/exception/GlobalExceptionHandler.java
  layer-common/src/main/java/org/layer/common/exception/ValidationCustomException.java
  layer-common/src/main/java/org/layer/common/validator/AtLeastNotNullValidator.java
  layer-domain/src/main/java/org/layer/domain/BaseEntity.java
  layer-domain/src/main/java/org/layer/domain/space/dto/SpaceWithMemberCount.java
  layer-domain/src/main/java/org/layer/domain/space/entity/MemberSpaceRelation.java
  layer-domain/src/main/java/org/layer/domain/space/entity/Space.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceCustomRepository.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepository.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepositoryImpl.java
Labels: 🛠️ enhancement, 🚀 feature

#27 feat/LS-18: 회고 목록 조회 API 구현
  .github/pull_request_template.md
  README.md
  layer-api/src/main/java/org/layer/domain/auth/controller/AuthController.java
  layer-api/src/main/java/org/layer/domain/auth/controller/dto/SignInRequest.java
  layer-api/src/main/java/org/layer/domain/auth/controller/dto/SignUpRequest.java
  layer-api/src/main/java/org/layer/domain/retrospect/controller/RetrospectApi.java
  layer-api/src/main/java/org/layer/domain/retrospect/controller/RetrospectController.java
  layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/response/RetrospectGetResponse.java
  layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/response/RetrospectListGetResponse.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/dto/request/RetrospectCreateServiceRequest.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/dto/response/RetrospectGetServiceResponse.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/dto/response/RetrospectListGetServiceResponse.java
  layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
  layer-common/src/main/java/org/layer/common/exception/MemberSpaceRelationExceptionType.java
  layer-common/src/main/java/org/layer/common/exception/SpaceExceptionType.java
  layer-domain/src/main/java/org/layer/domain/answer/entity/Answers.java
  layer-domain/src/main/java/org/layer/domain/answer/repository/AnswerRepository.java
  layer-domain/src/main/java/org/layer/domain/member/exception/MemberException.java
  layer-domain/src/main/java/org/layer/domain/member/repository/MemberRepository.java
  layer-domain/src/main/java/org/layer/domain/retrospect/repository/RetrospectRepository.java
  layer-domain/src/main/java/org/layer/domain/space/entity/MemberSpaceRelation.java
  layer-domain/src/main/java/org/layer/domain/space/entity/Team.java
  layer-domain/src/main/java/org/layer/domain/space/exception/MemberSpaceRelationException.java
  layer-domain/src/main/java/org/layer/domain/space/exception/SpaceException.java
  layer-domain/src/main/java/org/layer/domain/space/repository/MemberSpaceRelationRepository.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepository.java
Labels: 🚀 feature

#28 fix/LS-18: 빌드 실패 해결
  layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepository.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepositoryImpl.java
Labels: 🐞bug

#30 feat/Ls-23: 스페이스 회원 조회 API
  build.gradle
  layer-api/src/main/java/org/layer/domain/space/api/SpaceApi.java
  layer-api/src/main/java/org/layer/domain/space/controller/SpaceController.java
  layer-api/src/main/java/org/layer/domain/space/dto/SpaceResponse.java
  layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
  layer-domain/src/main/java/org/layer/domain/space/dto/SpaceWithMemberCount.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepositoryImpl.java
Labels: 🛠️ enhancement, 🚀 feature

#29 feat/Ls-22: 회고 생성 API 구현
  layer-api/src/main/java/org/layer/config/SecurityConfig.java
  layer-api/src/main/java/org/layer/domain/retrospect/controller/RetrospectController.java
  layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/request/RetrospectCreateRequest.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/dto/request/RetrospectCreateServiceRequest.java
  layer-domain/src/main/java/org/layer/domain/form/entity/Form.java
  layer-domain/src/main/java/org/layer/domain/question/converter/QuestionTypeConverter.java
  layer-domain/src/main/java/org/layer/domain/question/entity/Question.java
  layer-domain/src/main/java/org/layer/domain/question/enums/QuestionOwner.java
  layer-domain/src/main/java/org/layer/domain/question/enums/QuestionType.java
  layer-domain/src/main/java/org/layer/domain/questionOption/entity/QuestionOption.java
  layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
  layer-domain/src/main/java/org/layer/domain/space/entity/Space.java
Labels: 🚀 feature

#31 Feat/lS-25 : 스페이스 초대하기/떠나기 API
  layer-api/src/main/java/org/layer/domain/space/api/SpaceApi.java
  layer-api/src/main/java/org/layer/domain/space/controller/SpaceController.java
  layer-api/src/main/java/org/layer/domain/space/exception/SpaceExceptionType.java
  layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
  layer-domain/src/main/java/org/layer/domain/space/entity/Space.java
Labels: 🚀 feature

#32 feat/LS-20: 회고 템플릿 조회 API
  .gitignore
  layer-api/src/main/java/org/layer/domain/template/api/TemplateApi.java
  layer-api/src/main/java/org/layer/domain/template/controller/TemplateController.java
  layer-api/src/main/java/org/layer/domain/template/dto/AllTemplatesRequest.java
  layer-api/src/main/java/org/layer/domain/template/dto/QuestionResponse.java
  layer-api/src/main/java/org/layer/domain/template/dto/TemplateDetailInfoResponse.java
  layer-api/src/main/java/org/layer/domain/template/dto/TemplateDetailQuestionResponse.java
  layer-api/src/main/java/org/layer/domain/template/dto/TemplateInfoRequest.java
  layer-api/src/main/java/org/layer/domain/template/dto/TemplateListResponse.java
  layer-api/src/main/java/org/layer/domain/template/dto/TemplateQuestionListResponse.java
  layer-api/src/main/java/org/layer/domain/template/dto/TemplateQuestionResponse.java
  layer-api/src/main/java/org/layer/domain/template/dto/TemplateSimpleInfoResponse.java
  layer-api/src/main/java/org/layer/domain/template/service/TemplateService.java
  layer-domain/src/main/java/org/layer/domain/template/entity/Template.java
  layer-domain/src/main/java/org/layer/domain/template/entity/TemplateQuestion.java
  layer-domain/src/main/java/org/layer/domain/template/entity/dummy.txt
  layer-domain/src/main/java/org/layer/domain/template/exception/TemplateException.java
  layer-domain/src/main/java/org/layer/domain/template/exception/TemplateExceptionType.java
  layer-domain/src/main/java/org/layer/domain/template/repository/TemplateQuestionRepository.java
  layer-domain/src/main/java/org/layer/domain/template/repository/TemplateRepository.java
  layer-domain/src/main/java/org/layer/domain/template/repository/dummy.txt
Labels: 🚀 feature

#33 feat/LS-24: 특정 회고 질문 목록 조회 구현
  layer-api/src/main/java/org/layer/domain/question/controller/QuestionApi.java
  layer-api/src/main/java/org/layer/domain/question/controller/QuestionController.java
  layer-api/src/main/java/org/layer/domain/question/controller/dto/response/QuestionGetResponse.java
  layer-api/src/main/java/org/layer/domain/question/controller/dto/response/QuestionListGetResponse.java
  layer-api/src/main/java/org/layer/domain/question/service/QuestionService.java
  layer-api/src/main/java/org/layer/domain/question/service/dto/response/QuestionGetServiceResponse.java
  layer-api/src/main/java/org/layer/domain/question/service/dto/response/QuestionListGetServiceResponse.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
  layer-common/src/main/java/org/layer/common/exception/RetrospectExceptionType.java
  layer-domain/src/main/java/org/layer/domain/question/entity/Question.java
  layer-domain/src/main/java/org/layer/domain/question/repository/QuestionRepository.java
  layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
  layer-domain/src/main/java/org/layer/domain/retrospect/exception/RetrospectException.java
  layer-domain/src/main/java/org/layer/domain/retrospect/repository/RetrospectRepository.java
Labels: 🚀 feature

#34 feat/LS-26: 특정 회고 작성 API
  layer-api/src/main/java/org/layer/domain/answer/controller/AnswerApi.java
  layer-api/src/main/java/org/layer/domain/answer/controller/AnswerController.java
  layer-api/src/main/java/org/layer/domain/answer/controller/dto/request/AnswerCreateRequest.java
  layer-api/src/main/java/org/layer/domain/answer/controller/dto/request/AnswerListCreateRequest.java
  layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
  layer-api/src/main/java/org/layer/domain/answer/service/dto/request/AnswerCreateServiceRequest.java
  layer-api/src/main/java/org/layer/domain/answer/service/dto/request/AnswerListCreateServiceRequest.java
  layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/response/RetrospectGetResponse.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/dto/response/RetrospectGetServiceResponse.java
  layer-common/src/main/java/org/layer/common/exception/AnswerExceptionType.java
  layer-common/src/main/java/org/layer/common/exception/QuestionExceptionType.java
  layer-domain/src/main/java/org/layer/domain/answer/entity/Answer.java
  layer-domain/src/main/java/org/layer/domain/answer/entity/Answers.java
  layer-domain/src/main/java/org/layer/domain/answer/exception/AnswerException.java
  layer-domain/src/main/java/org/layer/domain/answer/repository/AnswerRepository.java
  layer-domain/src/main/java/org/layer/domain/question/converter/QuestionTypeConverter.java
  layer-domain/src/main/java/org/layer/domain/question/entity/Question.java
  layer-domain/src/main/java/org/layer/domain/question/entity/Questions.java
  layer-domain/src/main/java/org/layer/domain/question/enums/QuestionType.java
  layer-domain/src/main/java/org/layer/domain/question/exception/QuestionException.java
  layer-domain/src/main/java/org/layer/domain/question/repository/QuestionRepository.java
  layer-domain/src/main/java/org/layer/domain/template/entity/TemplateQuestion.java
Labels: 🚀 feature

#35 feat/LS-27: 액션 아이템 생성 API
  .gitignore
  layer-api/src/main/java/org/layer/domain/actionItem/api/ActionItemApi.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/ActionItemController.java
  layer-api/src/main/java/org/layer/domain/actionItem/dto/CreateActionItemRequest.java
  layer-api/src/main/java/org/layer/domain/actionItem/dto/CreateActionItemResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/dto/DeleteActionItemRequest.java
  layer-api/src/main/java/org/layer/domain/actionItem/dto/MemberActionItemResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/dto/TeamActionItemRequest.java
  layer-api/src/main/java/org/layer/domain/actionItem/dto/TeamActionItemResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/service/ActionItemService.java
  layer-domain/src/main/java/org/layer/domain/actionItem/entity/ActionItem.java
  layer-domain/src/main/java/org/layer/domain/actionItem/enums/ActionItemStatus.java
  layer-domain/src/main/java/org/layer/domain/actionItem/repository/ActionItemRepository.java
Labels: 🚀 feature

#37 feat/LS-27: 액션 아이템 회원 별/스페이스 별 조회, 삭제 API 구현
  layer-api/src/main/java/org/layer/domain/actionItem/api/ActionItemApi.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/ActionItemController.java
  layer-api/src/main/java/org/layer/domain/actionItem/dto/DeleteActionItemRequest.java
  layer-api/src/main/java/org/layer/domain/actionItem/dto/DeleteActionItemResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/dto/MemberActionItemResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/dto/SpaceActionItemElementResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/dto/SpaceActionItemResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/dto/TeamActionItemResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/service/ActionItemService.java
  layer-common/src/main/java/org/layer/common/exception/ActionItemExceptionType.java
  layer-common/src/main/java/org/layer/common/exception/MemberExceptionType.java
  layer-domain/src/main/java/org/layer/domain/actionItem/entity/ActionItem.java
  layer-domain/src/main/java/org/layer/domain/actionItem/enums/ActionItemStatus.java
  layer-domain/src/main/java/org/layer/domain/actionItem/exception/ActionItemException.java
  layer-domain/src/main/java/org/layer/domain/actionItem/repository/ActionItemRepository.java
  layer-domain/src/main/java/org/layer/domain/retrospect/repository/RetrospectRepository.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepository.java
Labels: 🚀 feature

#38 Feat/LS-30: 회원가입, 로그인 응답 값 수정 & 회원 정보 얻기 API 구현
  layer-api/src/main/java/org/layer/config/SecurityConfig.java
  layer-api/src/main/java/org/layer/config/SwaggerConfig.java
  layer-api/src/main/java/org/layer/domain/auth/controller/AuthApi.java
  layer-api/src/main/java/org/layer/domain/auth/controller/AuthController.java
  layer-api/src/main/java/org/layer/domain/auth/controller/dto/MemberInfoResponse.java
  layer-api/src/main/java/org/layer/domain/auth/controller/dto/ReissueTokenResponse.java
  layer-api/src/main/java/org/layer/domain/auth/controller/dto/SignInResponse.java
  layer-api/src/main/java/org/layer/domain/auth/controller/dto/SignUpResponse.java
  layer-api/src/main/java/org/layer/domain/auth/exception/TokenExceptionType.java
  layer-api/src/main/java/org/layer/domain/auth/service/AuthService.java
  layer-api/src/main/java/org/layer/domain/auth/service/dto/ReissueTokenServiceResponse.java
  layer-api/src/main/java/org/layer/domain/auth/service/dto/SignInServiceResponse.java
  layer-api/src/main/java/org/layer/domain/auth/service/dto/SignUpServiceResponse.java
  layer-api/src/main/java/org/layer/domain/jwt/exception/AuthException.java
  layer-api/src/main/java/org/layer/domain/jwt/exception/TokenException.java
  layer-api/src/main/java/org/layer/domain/jwt/service/JwtService.java
Labels: 🛠️ enhancement, 🚀 feature

#40 feat/LS-33: 이미지 업로드 API 구현하기
  build.gradle
  layer-api/src/main/java/org/layer/LayerApplication.java
  layer-api/src/main/java/org/layer/config/SecurityConfig.java
  layer-api/src/main/java/org/layer/domain/external/api/ExternalApi.java
  layer-api/src/main/java/org/layer/domain/external/controller/ExternalController.java
  layer-api/src/main/java/org/layer/domain/external/dto/ExternalRequest.java
  layer-api/src/main/java/org/layer/domain/external/dto/ExternalResponse.java
  layer-api/src/main/java/org/layer/domain/space/api/SpaceApi.java
  layer-api/src/main/java/org/layer/domain/space/controller/SpaceController.java
  layer-api/src/main/java/org/layer/domain/space/dto/SpaceRequest.java
  layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
  layer-common/src/main/java/org/layer/common/exception/ExternalExceptionType.java
  layer-domain/src/main/java/org/layer/domain/space/entity/Space.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceCustomRepository.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepositoryImpl.java
  layer-external/src/main/java/org/layer/external/ncp/config/NcpConfig.java
  layer-external/src/main/java/org/layer/external/ncp/enums/ImageDomain.java
  layer-external/src/main/java/org/layer/external/ncp/exception/ExternalExeption.java
  layer-external/src/main/java/org/layer/external/ncp/service/NcpService.java
Labels: 🚀 feature

#41 chore/LS-35 : 여러 API 뷰에 맞게 수정
  layer-api/src/main/java/org/layer/LayerApplication.java
  layer-api/src/main/java/org/layer/domain/answer/controller/dto/request/AnswerCreateRequest.java
  layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
  layer-api/src/main/java/org/layer/domain/question/controller/QuestionController.java
  layer-api/src/main/java/org/layer/domain/question/controller/dto/response/QuestionGetResponse.java
  layer-api/src/main/java/org/layer/domain/question/service/QuestionService.java
  layer-api/src/main/java/org/layer/domain/question/service/dto/response/QuestionGetServiceResponse.java
  layer-api/src/main/java/org/layer/domain/retrospect/controller/RetrospectController.java
  layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/request/RetrospectCreateRequest.java
  layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/response/RetrospectGetResponse.java
  layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/response/RetrospectListGetResponse.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/dto/response/RetrospectGetServiceResponse.java
  layer-common/src/main/java/org/layer/common/exception/RetrospectExceptionType.java
  layer-domain/src/main/java/org/layer/domain/common/time/RealTime.java
  layer-domain/src/main/java/org/layer/domain/common/time/Time.java
  layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
  layer-domain/src/main/java/org/layer/domain/space/repository/MemberSpaceRelationRepository.java
Labels: 🐞bug

#47 fix/LS-35: 컴포넌트 스캔 오류 해결
  layer-api/src/main/java/org/layer/LayerApplication.java
  layer-domain/src/main/java/org/layer/domain/common/time/RealTime.java
Labels: 🐞bug

#50 feat: presigned URL 이미지 저장 로직 변경
  layer-api/src/main/java/org/layer/domain/external/api/ExternalApi.java
  layer-api/src/main/java/org/layer/domain/external/controller/ExternalController.java
  layer-api/src/main/java/org/layer/domain/external/dto/ExternalResponse.java
  layer-external/src/main/java/org/layer/external/ncp/dto/NcpResponse.java
  layer-external/src/main/java/org/layer/external/ncp/service/NcpService.java
Labels: 🛠️ enhancement, 🚀 feature

#46 feat: 스페이스 생성 시 필드 복수개로 변경
  layer-api/src/main/java/org/layer/domain/space/dto/SpaceRequest.java
  layer-api/src/main/java/org/layer/domain/space/dto/SpaceResponse.java
  layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
  layer-common/src/main/java/org/layer/common/exception/GlobalExceptionHandler.java
  layer-domain/src/main/java/org/layer/domain/form/entity/Form.java
  layer-domain/src/main/java/org/layer/domain/space/converter/SpaceFieldConverter.java
  layer-domain/src/main/java/org/layer/domain/space/dto/SpaceWithMemberCount.java
  layer-domain/src/main/java/org/layer/domain/space/entity/Space.java
  layer-domain/src/main/java/org/layer/domain/space/entity/SpaceField.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceCustomRepository.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepositoryImpl.java
Labels: 🛠️ enhancement, 🚀 feature

#43 feat/LS-34 : 로깅 및 yml 통합
  .github/workflows/ci-cd-compose.yaml
  .github/workflows/ci-cd.yaml
  build.gradle
  layer-api/Dockerfile
  layer-api/infra/development/docker-compose.yaml
  layer-api/infra/production/docker-compose.yaml
  layer-api/src/main/java/org/layer/LayerApplication.java
  layer-api/src/main/java/org/layer/aop/ExecutionLoggingAop.java
  layer-api/src/main/java/org/layer/filter/LoggerFilter.java
  layer-api/src/main/resources/application-dev.yml
  layer-api/src/main/resources/application-local.yml
  layer-api/src/main/resources/application-prod.yml
  layer-api/src/main/resources/application-test.yml
  layer-api/src/main/resources/console-appender.xml
  layer-api/src/main/resources/logback-spring.xml
Labels: 🚀 feature, 📚 setting

#54 fix: 회원 가입이 필요한 상황에서의 응답 내용 수정
  layer-api/src/main/java/org/layer/domain/auth/service/AuthService.java
  layer-api/src/main/java/org/layer/domain/member/service/MemberService.java
  layer-common/src/main/java/org/layer/common/exception/MemberExceptionType.java
Labels: 🐞bug

#56 feat: 스페이스 조회 API 배너 추가
  layer-api/src/main/java/org/layer/domain/external/dto/ExternalResponse.java
  layer-api/src/main/java/org/layer/domain/space/dto/SpaceResponse.java
  layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
  layer-common/src/main/java/org/layer/common/exception/ExternalExceptionType.java
  layer-domain/src/main/java/org/layer/domain/space/dto/SpaceWithMemberCount.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepositoryImpl.java
  layer-external/src/main/java/org/layer/external/ncp/exception/ExternalException.java
  layer-external/src/main/java/org/layer/external/ncp/service/NcpService.java
Labels: 🚀 feature

#57 fix: checkout 액션 명령어 오류 수정
  .github/workflows/ci-cd-compose.yaml
Labels: 🐞bug

#59 feat: 생성된 스페이스 아이디 반환하기
  layer-api/src/main/java/org/layer/domain/jwt/JwtAuthenticationFilter.java
  layer-api/src/main/java/org/layer/domain/space/api/SpaceApi.java
  layer-api/src/main/java/org/layer/domain/space/controller/SpaceController.java
  layer-api/src/main/java/org/layer/domain/space/dto/SpaceResponse.java
  layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
Labels: 🛠️ enhancement

#64 feat/#52 : 회고 임시 저장 기능 구현
  layer-api/src/main/java/org/layer/domain/answer/controller/AnswerApi.java
  layer-api/src/main/java/org/layer/domain/answer/controller/AnswerController.java
  layer-api/src/main/java/org/layer/domain/answer/controller/dto/request/AnswerCreateRequest.java
  layer-api/src/main/java/org/layer/domain/answer/controller/dto/request/AnswerListCreateRequest.java
  layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/TemporaryAnswerGetResponse.java
  layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/TemporaryAnswerListResponse.java
  layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
  layer-api/src/main/java/org/layer/domain/answer/service/dto/request/AnswerCreateServiceRequest.java
  layer-api/src/main/java/org/layer/domain/answer/service/dto/request/AnswerListCreateServiceRequest.java
  layer-api/src/main/java/org/layer/domain/question/controller/QuestionController.java
  layer-api/src/main/java/org/layer/domain/question/controller/dto/response/QuestionListGetResponse.java
  layer-api/src/main/java/org/layer/domain/question/service/QuestionService.java
  layer-common/src/main/java/org/layer/common/exception/AnswerExceptionType.java
  layer-domain/src/main/java/org/layer/domain/answer/entity/Answer.java
  layer-domain/src/main/java/org/layer/domain/answer/entity/Answers.java
  layer-domain/src/main/java/org/layer/domain/answer/enums/AnswerStatus.java
  layer-domain/src/main/java/org/layer/domain/answer/repository/AnswerRepository.java
Labels: 🚀 feature
