Repository depromeet/layer-server, pull requests merged in 2024-12, with the labels that each got.

#266 feat: admin 모듈 개발 및 회원 목록 조회 구현
  .github/workflows/aws-cicd-dev.yml
  .github/workflows/aws-cicd-prod.yml
  .gitignore
  build.gradle
  config/tokens/StoredCredential.txt
  layer-admin/Dockerfile-admin
  layer-admin/src/main/java/org/layer/AdminApplication.java
  layer-admin/src/main/java/org/layer/config/SecurityConfig.java
  layer-admin/src/main/java/org/layer/member/controller/AdminMemberApi.java
  layer-admin/src/main/java/org/layer/member/controller/AdminMemberController.java
  layer-admin/src/main/java/org/layer/member/controller/dto/GetMemberActivityResponse.java
  layer-admin/src/main/java/org/layer/member/controller/dto/GetMembersActivitiesResponse.java
  layer-admin/src/main/java/org/layer/member/service/AdminMemberService.java
  layer-admin/src/main/resources/application-dev.yml
  layer-admin/src/main/resources/application-prod.yml
  layer-api/infra/development/docker-compose.yaml
  layer-api/infra/development/nginx.conf
  layer-domain/src/main/java/org/layer/domain/answer/repository/AdminAnswerRepository.java
  layer-domain/src/main/java/org/layer/domain/member/repository/AdminMemberRepository.java
  layer-domain/src/main/java/org/layer/domain/space/repository/AdminMemberSpaceRelationRepository.java
  settings.gradle
Labels: 🚀 feature

#268 chore: dev db connection 개수 조정
  .gitignore
  build.gradle
  layer-admin/src/main/java/org/layer/common/exception/AdminException.java
  layer-admin/src/main/java/org/layer/config/RedisConfigDev.java
  layer-admin/src/main/java/org/layer/config/RedisConfigProd.java
  layer-admin/src/main/java/org/layer/member/controller/dto/GetMemberActivityResponse.java
  layer-admin/src/main/java/org/layer/member/service/AdminMemberService.java
  layer-admin/src/main/resources/application-dev.yml
  layer-admin/src/main/resources/application-local.yml
  layer-admin/src/main/resources/application-prod.yml
  layer-api/src/main/java/org/layer/aop/RecentAccessHistoryAop.java
  layer-api/src/main/java/org/layer/config/RedisConfigDev.java
  layer-api/src/main/java/org/layer/config/RedisConfigProd.java
  layer-api/src/main/resources/application-dev.yml
  layer-common/src/main/java/org/layer/common/exception/AdminExceptionType.java
Labels: 👨‍💻 chore

#270 chore: 어드민 모듈 리버스 프록싱 v2
  .github/workflows/aws-cicd-dev.yml
  .github/workflows/aws-cicd-prod.yml
  layer-admin/src/main/java/org/layer/member/controller/AdminMemberController.java
  layer-admin/src/main/resources/application-dev.yml
  layer-admin/src/main/resources/application-prod.yml
  layer-api/infra/development/nginx.conf
  layer-api/infra/production/docker-compose-blue.yaml
  layer-api/infra/production/docker-compose-green.yaml
  layer-api/infra/production/nginx.blue.conf
  layer-api/infra/production/nginx.conf
  layer-api/infra/production/nginx.green.conf
  layer-batch/src/main/resources/application.yml
Labels: 👨‍💻 chore

#274 fix: 특정 회고의 답변을 완료하지 않아도 완료된 회고를 볼 수 있도록 수정
  layer-api/src/main/java/org/layer/domain/answer/controller/AnswerController.java
  layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
  layer-api/src/main/resources/application-test.yml
  layer-api/src/main/resources/console-appender.xml
  layer-api/src/main/resources/logback-spring.xml
  layer-api/src/test/java/org/layer/LayerApplicationTests.java
  layer-api/src/test/java/org/layer/domain/answer/service/AnswerServiceTest.java
  layer-api/src/test/java/org/layer/domain/retrospect/service/RetrospectServiceTest.java
  layer-domain/src/main/java/org/layer/domain/answer/entity/Answers.java
  layer-domain/src/test/java/layer/domain/retrospect/entity/RetrospectTest.java
Labels: 👨‍💻 chore

#276 fix: gitignore 수정 및 테스트 데이터 주입
  .github/workflows/aws-cicd-dev.yml
  .github/workflows/aws-cicd-prod.yml
  .gitignore
  layer-api/src/test/resources/sql/answer-service-test-data.sql
  layer-api/src/test/resources/sql/delete-all-test-data.sql
Labels: 🐞bug

#277 refactor: 기존 Admin API를 Admin 모듈로 이전
  layer-admin/src/main/java/org/layer/retrospect/controller/AdminRetrospectApi.java
  layer-admin/src/main/java/org/layer/retrospect/controller/AdminRetrospectController.java
  layer-admin/src/main/java/org/layer/retrospect/controller/dto/AdminRetrospectCountGetResponse.java
  layer-admin/src/main/java/org/layer/retrospect/controller/dto/AdminRetrospectsGetResponse.java
  layer-admin/src/main/java/org/layer/retrospect/service/AdminRetrospectService.java
  layer-admin/src/main/java/org/layer/space/controller/AdminSpaceApi.java
  layer-admin/src/main/java/org/layer/space/controller/AdminSpaceController.java
  layer-admin/src/main/java/org/layer/space/controller/dto/AdminSpaceCountGetResponse.java
  layer-admin/src/main/java/org/layer/space/controller/dto/AdminSpacesGetResponse.java
  layer-admin/src/main/java/org/layer/space/service/AdminSpaceService.java
  layer-api/src/main/java/org/layer/aop/RecentAccessHistoryAop.java
  layer-api/src/main/java/org/layer/domain/admin/controller/AdminApi.java
  layer-api/src/main/java/org/layer/domain/admin/controller/AdminController.java
  layer-api/src/main/java/org/layer/domain/admin/service/AdminService.java
  layer-api/src/main/java/org/layer/domain/auth/service/AuthService.java
  layer-external/src/main/java/org/layer/oauth/service/OAuthService.java
Labels: 👨‍💻 chore, refactor

#281 fix: redis 종료되지 않도록 수정
  .github/workflows/ci-cd-compose.yaml
  .github/workflows/k3s-dev.yaml
  .github/workflows/k3s-prod.yaml
  config/tokens/StoredCredential.txt
  layer-api/infra/production/deploy.sh
  layer-api/k8s/development/deployment.yaml
  tokens/StoredCredential
Labels: 🐞bug
