Repository depromeet/layer-server, pull requests merged in 2024-09, with the labels that each got.

#206 feat: admin API 개발
  layer-api/src/main/java/org/layer/config/SecurityConfig.java
  layer-api/src/main/java/org/layer/domain/admin/controller/AdminApi.java
  layer-api/src/main/java/org/layer/domain/admin/controller/AdminController.java
  layer-api/src/main/java/org/layer/domain/admin/controller/dto/AdminRetrospectsGetResponse.java
  layer-api/src/main/java/org/layer/domain/admin/controller/dto/AdminSpacesGetResponse.java
  layer-api/src/main/java/org/layer/domain/admin/service/AdminService.java
  layer-api/src/main/resources/application-dev.yml
  layer-api/src/main/resources/application-local.yml
  layer-api/src/main/resources/application-prod.yml
  layer-api/src/main/resources/application-test.yml
  layer-domain/src/main/java/org/layer/domain/retrospect/dto/AdminRetrospectGetResponse.java
  layer-domain/src/main/java/org/layer/domain/retrospect/repository/RetrospectAdminRepository.java
  layer-domain/src/main/java/org/layer/domain/space/dto/AdminSpaceGetResponse.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceAdminRepository.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepository.java
Labels: 🚀 feature

#207 v1.0.3
  .github/workflows/k3s-dev.yaml
  .github/workflows/k3s-prod.yaml
  layer-api/Dockerfile
  layer-api/src/main/java/org/layer/config/SecurityConfig.java
  layer-api/src/main/java/org/layer/domain/admin/controller/AdminApi.java
  layer-api/src/main/java/org/layer/domain/admin/controller/AdminController.java
  layer-api/src/main/java/org/layer/domain/admin/controller/dto/AdminRetrospectsGetResponse.java
  layer-api/src/main/java/org/layer/domain/admin/controller/dto/AdminSpacesGetResponse.java
  layer-api/src/main/java/org/layer/domain/admin/service/AdminService.java
  layer-api/src/main/resources/application-dev.yml
  layer-api/src/main/resources/application-local.yml
  layer-api/src/main/resources/application-prod.yml
  layer-api/src/main/resources/application-test.yml
  layer-domain/src/main/java/org/layer/domain/retrospect/dto/AdminRetrospectGetResponse.java
  layer-domain/src/main/java/org/layer/domain/retrospect/repository/RetrospectAdminRepository.java
  layer-domain/src/main/java/org/layer/domain/space/dto/AdminSpaceGetResponse.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceAdminRepository.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepository.java
Labels: 🚀 feature

#211 feat: 백오피스용 API
  gradle/wrapper/gradle-wrapper.properties
  layer-api/src/main/java/org/layer/domain/admin/controller/AdminApi.java
  layer-api/src/main/java/org/layer/domain/admin/controller/AdminController.java
  layer-api/src/main/java/org/layer/domain/admin/controller/dto/AdminRetrospectCountGetResponse.java
  layer-api/src/main/java/org/layer/domain/admin/controller/dto/AdminSpaceCountGetResponse.java
  layer-api/src/main/java/org/layer/domain/admin/service/AdminService.java
  layer-api/src/main/resources/application-local.yml
  layer-domain/src/main/java/org/layer/domain/retrospect/dto/AdminRetrospectCountGroupBySpaceGetResponse.java
  layer-domain/src/main/java/org/layer/domain/retrospect/repository/RetrospectAdminRepository.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceAdminRepository.java
Labels: 🚀 feature

#216 chore: 회고 마감일 nullable 하게 수정
  layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/request/RetrospectCreateRequest.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
  layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
Labels: 👨‍💻 chore

#217 fix: 템플릿 추천 로직 수정
  layer-api/src/main/java/org/layer/domain/form/controller/FormController.java
  layer-api/src/main/java/org/layer/domain/form/service/FormService.java
  layer-domain/src/main/java/org/layer/domain/form/enums/FormTag.java
  layer-domain/src/main/java/org/layer/domain/form/enums/RetrospectPurpose.java
  layer-domain/src/main/java/org/layer/domain/form/repository/FormRepository.java
Labels: 🐞bug

#220 chore: 추천 템플릿이 중복인 경우, 그 중에서 랜덤으로 하나 선택하도록 수정
  layer-api/src/main/java/org/layer/domain/form/service/FormService.java
  layer-domain/src/main/java/org/layer/domain/common/random/CustomRandom.java
  layer-domain/src/main/java/org/layer/domain/common/random/MockRandom.java
  layer-domain/src/main/java/org/layer/domain/common/random/RealRandom.java
  layer-domain/src/main/java/org/layer/domain/form/enums/FormTag.java
Labels: 👨‍💻 chore

#223 chore: 회고 목록 변경으로 인한 수정
  layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
  layer-api/src/main/java/org/layer/domain/retrospect/controller/RetrospectApi.java
  layer-api/src/main/java/org/layer/domain/retrospect/controller/RetrospectController.java
  layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/response/RetrospectGetResponse.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/dto/request/RetrospectCreateServiceRequest.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/dto/response/RetrospectGetServiceResponse.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/dto/response/RetrospectListGetServiceResponse.java
  layer-api/src/main/resources/application-dev.yml
  layer-batch/src/main/java/org/layer/batch/scheduler/RetrospectScheduler.java
  layer-domain/src/main/java/org/layer/domain/answer/entity/Answers.java
  layer-domain/src/main/java/org/layer/domain/retrospect/entity/AnalysisStatus.java
  layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
  layer-domain/src/main/java/org/layer/domain/retrospect/entity/WriteStatus.java
  layer-external/src/main/java/org/layer/external/ai/service/AIAnalyzeService.java
Labels: 👨‍💻 chore

#227 hotfix: 회고 생성 오류 해결
  layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
  layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
Labels: 🐞bug

#231 fix: AI 서비스와 싱크 맞지 않는 오류 해결
  layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
Labels: 🐞bug

#234 fix: 분석상태가 DONE 으로 되지 않는 오류 해결
  layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
Labels: 🐞bug

#229 fix/222: 멤버가 탈퇴했을 때 처리
  layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/AnswerByPersonGetResponse.java
  layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/AnswerByQuestionGetResponse.java
  layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/PersonAndAnswerGetResponse.java
  layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
  layer-api/src/main/java/org/layer/domain/auth/service/AuthService.java
  layer-api/src/main/java/org/layer/domain/member/service/MemberService.java
  layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
  layer-domain/src/main/java/org/layer/domain/member/entity/Member.java
  layer-domain/src/main/java/org/layer/domain/member/entity/Members.java
  layer-domain/src/main/java/org/layer/domain/space/dto/SpaceMember.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepositoryImpl.java
Labels: 🐞bug

#237 chore: 회고 답변 직후에 응답 확인할 수 있도록 수정
  layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
  layer-domain/src/main/java/org/layer/domain/answer/entity/Answers.java
Labels: 👨‍💻 chore

#240 fix: 회고 마감 로직 수정
  layer-external/src/main/java/org/layer/external/ai/service/AIAnalyzeService.java
Labels: 🐞bug

#243 fix: 이미 마감되었을 경우 분석 로직 실행시키지 않도록 수정
  layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
Labels: 🐞bug

#245 fix: 임시답변 제외하고 조회하도록 수정
  layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
Labels: 🐞bug

#248 chore: 불필요한 API 제거
  layer-api/src/main/java/org/layer/domain/auth/controller/AuthController.java
  layer-api/src/main/resources/tokens/StoredCredential
Labels: 👨‍💻 chore
