Repository depromeet/layer-server, pull requests merged in 2024-08, with the labels that each got.

#65 feat : 질문 수정 관련 로직 구현
  layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
  layer-api/src/main/java/org/layer/domain/form/controller/FormApi.java
  layer-api/src/main/java/org/layer/domain/form/controller/FormController.java
  layer-api/src/main/java/org/layer/domain/form/controller/dto/response/DefaultFormGetResponse.java
  layer-api/src/main/java/org/layer/domain/form/controller/dto/response/DefaultQuestionGetResponse.java
  layer-api/src/main/java/org/layer/domain/form/service/FormService.java
  layer-api/src/main/java/org/layer/domain/question/service/QuestionService.java
  layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/request/QuestionCreateRequest.java
  layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/request/RetrospectCreateRequest.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
  layer-common/src/main/java/org/layer/common/exception/FormExceptionType.java
  layer-common/src/main/java/org/layer/common/exception/SpaceExceptionType.java
  layer-domain/src/main/java/org/layer/domain/actionItem/entity/ActionItem.java
  layer-domain/src/main/java/org/layer/domain/form/entity/Form.java
  layer-domain/src/main/java/org/layer/domain/form/entity/FormType.java
  layer-domain/src/main/java/org/layer/domain/form/exception/FormException.java
  layer-domain/src/main/java/org/layer/domain/form/repository/FormRepository.java
  layer-domain/src/main/java/org/layer/domain/question/entity/Question.java
  layer-domain/src/main/java/org/layer/domain/question/repository/QuestionRepository.java
  layer-domain/src/main/java/org/layer/domain/space/entity/Space.java
Labels: 🚀 feature, 👨‍💻 chore

#70 fix: 스페이스 떠나기 요청방식변경
  layer-api/src/main/java/org/layer/domain/space/controller/SpaceApi.java
  layer-api/src/main/java/org/layer/domain/space/controller/SpaceController.java
  layer-api/src/main/java/org/layer/domain/space/controller/dto/SpaceRequest.java
Labels: 🐞bug, 🛠️ enhancement

#73 feat: 템플릿 추천 로직 구현
  layer-api/src/main/java/org/layer/domain/form/controller/FormApi.java
  layer-api/src/main/java/org/layer/domain/form/controller/FormController.java
  layer-api/src/main/java/org/layer/domain/form/controller/dto/request/RecommendFormQueryDto.java
  layer-api/src/main/java/org/layer/domain/form/controller/dto/request/RecommendFormSetRequest.java
  layer-api/src/main/java/org/layer/domain/form/controller/dto/response/RecommendFormResponseDto.java
  layer-api/src/main/java/org/layer/domain/form/service/FormService.java
  layer-domain/src/main/java/org/layer/domain/form/entity/Form.java
  layer-domain/src/main/java/org/layer/domain/form/enums/RetrospectPeriod.java
  layer-domain/src/main/java/org/layer/domain/form/enums/RetrospectPurpose.java
  layer-domain/src/main/java/org/layer/domain/tag/entity/Tag.java
  layer-domain/src/main/java/org/layer/domain/tag/repository/TagRepository.java
Labels: 🚀 feature

#75 chore: 회고 생성 플로우 변화로 인한 수정
  layer-api/src/main/java/org/layer/domain/form/controller/FormApi.java
  layer-api/src/main/java/org/layer/domain/form/controller/FormController.java
  layer-api/src/main/java/org/layer/domain/form/controller/dto/response/DefaultFormGetResponse.java
  layer-api/src/main/java/org/layer/domain/form/controller/dto/response/FormGetResponse.java
  layer-api/src/main/java/org/layer/domain/form/controller/dto/response/QuestionGetResponse.java
  layer-api/src/main/java/org/layer/domain/form/service/FormService.java
  layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/request/RetrospectCreateRequest.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
  layer-domain/src/main/java/org/layer/domain/space/entity/Space.java
  layer-domain/src/main/java/org/layer/domain/tag/entity/Tag.java
Labels: 👨‍💻 chore

#81 fix: 회고 작성 @Transactional 추가
  layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
Labels: 🐞bug

#80 fix/67: 기본 템플릿 조회 API 바뀐 테이블 구조에 맞게 수정
  layer-api/src/main/java/org/layer/domain/template/controller/TemplateApi.java
  layer-api/src/main/java/org/layer/domain/template/controller/TemplateController.java
  layer-api/src/main/java/org/layer/domain/template/controller/dto/TemplateDetailInfoResponse.java
  layer-api/src/main/java/org/layer/domain/template/controller/dto/TemplateDetailQuestionResponse.java
  layer-api/src/main/java/org/layer/domain/template/controller/dto/TemplateListResponse.java
  layer-api/src/main/java/org/layer/domain/template/controller/dto/TemplateQuestionListResponse.java
  layer-api/src/main/java/org/layer/domain/template/controller/dto/TemplateQuestionResponse.java
  layer-api/src/main/java/org/layer/domain/template/controller/dto/TemplateSimpleInfoResponse.java
  layer-api/src/main/java/org/layer/domain/template/service/TemplateService.java
  layer-common/src/main/java/org/layer/common/exception/QuestionExceptionType.java
  layer-domain/src/main/java/org/layer/domain/template/entity/QuestionDescription.java
  layer-domain/src/main/java/org/layer/domain/template/entity/TemplateMetadata.java
  layer-domain/src/main/java/org/layer/domain/template/entity/TemplatePurpose.java
  layer-domain/src/main/java/org/layer/domain/template/entity/TemplateQuestion.java
  layer-domain/src/main/java/org/layer/domain/template/repository/QuestionDescriptionRepository.java
  layer-domain/src/main/java/org/layer/domain/template/repository/TemplateMetadataRepository.java
  layer-domain/src/main/java/org/layer/domain/template/repository/TemplatePurposeRepository.java
  layer-domain/src/main/java/org/layer/domain/template/repository/TemplateQuestionRepository.java
  layer-domain/src/main/java/org/layer/domain/template/repository/TemplateRepository.java
Labels: 🐞bug

#86 fix: 회고 임시 저장 조회 로직 npe 오류 해결
  layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
  layer-domain/src/main/java/org/layer/domain/answer/entity/Answers.java
Labels: 🐞bug

#89 refactor: 로깅 URI 추가
  layer-api/src/main/java/org/layer/aop/ExecutionLoggingAop.java
Labels: 🚀 feature

#94 chore/92: FormTag enum 추가, Form, TemplateMetadata 엔티티 수정
  layer-api/src/main/java/org/layer/domain/template/controller/dto/TemplateDetailInfoResponse.java
  layer-api/src/main/java/org/layer/domain/template/controller/dto/TemplateSimpleInfoResponse.java
  layer-domain/src/main/java/org/layer/domain/form/entity/Form.java
  layer-domain/src/main/java/org/layer/domain/form/enums/FormTag.java
  layer-domain/src/main/java/org/layer/domain/template/entity/TemplateMetadata.java
Labels: 👨‍💻 chore

#101 feat: 멤버 정보 변경 API 작성
  layer-api/src/main/java/org/layer/domain/member/controller/MemberApi.java
  layer-api/src/main/java/org/layer/domain/member/controller/MemberController.java
  layer-api/src/main/java/org/layer/domain/member/controller/dto/UpdateMemberInfoRequest.java
  layer-api/src/main/java/org/layer/domain/member/controller/dto/UpdateMemberInfoResponse.java
  layer-api/src/main/java/org/layer/domain/member/service/MemberService.java
  layer-domain/src/main/java/org/layer/domain/form/enums/FormPublishedBy.java
  layer-domain/src/main/java/org/layer/domain/member/entity/Member.java
  layer-domain/src/main/java/org/layer/domain/member/repository/MemberRepository.java
Labels: 🚀 feature

#104 chore: answerContent 로 변경
  layer-api/src/main/java/org/layer/domain/answer/controller/dto/request/AnswerCreateRequest.java
  layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
Labels: 👨‍💻 chore

#106 feat: 회고 조회 응답 필드 추가하기 (#105)
  layer-api/src/main/java/org/layer/domain/retrospect/controller/RetrospectController.java
  layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/response/RetrospectGetResponse.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/dto/response/RetrospectGetServiceResponse.java
Labels: 🚀 feature

#108 feat: 회고 분석 조회 API
  layer-api/src/main/java/org/layer/domain/answer/controller/AnswerApi.java
  layer-api/src/main/java/org/layer/domain/answer/controller/AnswerController.java
  layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/AnswerByPersonGetResponse.java
  layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/AnswerByQuestionGetResponse.java
  layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/AnswerListGetResponse.java
  layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/PersonAndAnswerGetResponse.java
  layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/QuestionAndAnswerGetResponse.java
  layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
  layer-common/src/main/java/org/layer/common/exception/RetrospectExceptionType.java
  layer-domain/src/main/java/org/layer/domain/answer/entity/Answers.java
  layer-domain/src/main/java/org/layer/domain/answer/repository/AnswerRepository.java
  layer-domain/src/main/java/org/layer/domain/member/entity/Members.java
  layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
Labels: 🚀 feature

#109 feat: 스페이스에 속한 커스텀 폼 목록 조회
  layer-api/src/main/java/org/layer/domain/form/controller/FormApi.java
  layer-api/src/main/java/org/layer/domain/form/controller/FormController.java
  layer-api/src/main/java/org/layer/domain/form/controller/dto/response/CustomTemplateListResponse.java
  layer-api/src/main/java/org/layer/domain/form/controller/dto/response/CustomTemplateResponse.java
  layer-api/src/main/java/org/layer/domain/form/service/FormService.java
  layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/request/QuestionCreateRequest.java
  layer-common/src/main/java/org/layer/common/exception/FormExceptionType.java
  layer-domain/src/main/java/org/layer/domain/form/repository/FormRepository.java
Labels: 🚀 feature

#110 feat:스페이스 팀원 목록 조회하기 (#107)
  layer-api/src/main/java/org/layer/domain/space/controller/SpaceApi.java
  layer-api/src/main/java/org/layer/domain/space/controller/SpaceController.java
  layer-api/src/main/java/org/layer/domain/space/controller/dto/SpaceResponse.java
  layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
  layer-domain/src/main/java/org/layer/domain/space/dto/SpaceMember.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceCustomRepository.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepositoryImpl.java
Labels: 🚀 feature

#112 chore: Tag 데이터 삭제
  layer-api/src/main/java/org/layer/domain/form/controller/dto/response/FormGetResponse.java
  layer-api/src/main/java/org/layer/domain/form/controller/dto/response/RecommendFormResponseDto.java
  layer-api/src/main/java/org/layer/domain/form/service/FormService.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
  layer-api/src/main/java/org/layer/domain/space/controller/SpaceController.java
  layer-domain/src/main/java/org/layer/domain/form/entity/Form.java
  layer-domain/src/main/java/org/layer/domain/tag/entity/Tag.java
  layer-domain/src/main/java/org/layer/domain/tag/repository/TagRepository.java
Labels: 👨‍💻 chore

#116 fix: create actionitem 수정
  layer-api/src/main/java/org/layer/domain/actionItem/service/ActionItemService.java
Labels: 🐞bug

#118 feat: 내가 작성한 회고 수정하기
  layer-api/src/main/java/org/layer/domain/answer/controller/AnswerApi.java
  layer-api/src/main/java/org/layer/domain/answer/controller/AnswerController.java
  layer-api/src/main/java/org/layer/domain/answer/controller/dto/request/AnswerListUpdateRequest.java
  layer-api/src/main/java/org/layer/domain/answer/controller/dto/request/AnswerUpdateRequest.java
  layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/WrittenAnswerGetResponse.java
  layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/WrittenAnswerListResponse.java
  layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
  layer-common/src/main/java/org/layer/common/exception/AnswerExceptionType.java
  layer-domain/src/main/java/org/layer/domain/answer/entity/Answer.java
  layer-domain/src/main/java/org/layer/domain/answer/entity/Answers.java
  layer-domain/src/main/java/org/layer/domain/answer/repository/AnswerRepository.java
  layer-domain/src/main/java/org/layer/domain/question/repository/QuestionRepository.java
Labels: 🚀 feature

#119 feat: 회고 수정 및 삭제 로직 구현
  layer-api/src/main/java/org/layer/domain/form/controller/dto/request/RecommendFormQueryDto.java
  layer-api/src/main/java/org/layer/domain/retrospect/controller/RetrospectApi.java
  layer-api/src/main/java/org/layer/domain/retrospect/controller/RetrospectController.java
  layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/request/RetrospectUpdateRequest.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
  layer-common/src/main/java/org/layer/common/exception/RetrospectExceptionType.java
  layer-domain/src/main/java/org/layer/domain/form/enums/RetrospectPeriodic.java
  layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
  layer-domain/src/main/java/org/layer/domain/space/entity/Space.java
Labels: 🚀 feature

#121 test: 테스트코드 환경 세팅
  build.gradle
  layer-api/src/main/resources/application-test.yml
  layer-api/src/test/java/org/layer/LayerApplicationTests.java
  layer-api/src/test/java/org/layer/domain/retrospect/service/RetrospectServiceTest.java
  layer-domain/src/test/java/layer/domain/TestConfiguration.java
  layer-domain/src/test/java/layer/domain/retrospect/entity/RetrospectTest.java
  layer-domain/src/test/java/layer/domain/retrospect/repository/RetrospectRepositoryTest.java
Labels: 🚀 feature

#123 chore: enum 변경 및 스웨거 추가
  layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/AnswerByPersonGetResponse.java
  layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/AnswerByQuestionGetResponse.java
  layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/AnswerListGetResponse.java
  layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/PersonAndAnswerGetResponse.java
  layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/QuestionAndAnswerGetResponse.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
  layer-domain/src/main/java/org/layer/domain/form/enums/FormTag.java
Labels: 👨‍💻 chore

#126 fix: 스페이스 커스텀 폼 조회 응답에 폼아이디 추가
  layer-api/src/main/java/org/layer/domain/form/controller/dto/response/CustomTemplateResponse.java
  layer-api/src/main/java/org/layer/domain/form/service/FormService.java
Labels: 🐞bug

#128 fix: 스페이스 커스텀 폼 조회 로직 수정
  layer-api/src/main/java/org/layer/domain/form/service/FormService.java
  layer-domain/src/main/java/org/layer/domain/form/repository/FormRepository.java
Labels: 🐞bug

#129 feat/124: 실행 목표 조회 API 구현
  layer-api/src/main/java/org/layer/domain/actionItem/controller/ActionItemApi.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/ActionItemController.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/ActionItemResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/CreateActionItemResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/DeleteActionItemResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/GetSpaceActionItemResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/GetSpaceRetrospectActionItemResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/MemberActionItemElementResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/MemberActionItemResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/RetrospectActionItemResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/SpaceActionItemElementResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/SpaceActionItemResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/service/ActionItemService.java
  layer-domain/src/main/java/org/layer/domain/actionItem/entity/ActionItem.java
  layer-domain/src/main/java/org/layer/domain/actionItem/entity/ActionItems.java
  layer-domain/src/main/java/org/layer/domain/actionItem/enums/ActionItemStatus.java
  layer-domain/src/main/java/org/layer/domain/actionItem/repository/ActionItemRepository.java
  layer-domain/src/main/java/org/layer/domain/retrospect/repository/RetrospectRepository.java
  layer-domain/src/main/java/org/layer/domain/space/repository/MemberSpaceRelationRepository.java
Labels: 🚀 feature

#131 fix: 스페이스 삭제시 회고와 액션아이템 삭제
  layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
  layer-domain/src/main/java/org/layer/domain/actionItem/repository/ActionItemRepository.java
  layer-domain/src/main/java/org/layer/domain/retrospect/repository/RetrospectRepository.java
Labels: 🐞bug, 🛠️ enhancement

#135 feat: 디폴트 폼 작업 진행
  layer-api/src/main/java/org/layer/domain/form/controller/FormApi.java
  layer-api/src/main/java/org/layer/domain/form/controller/FormController.java
  layer-api/src/main/java/org/layer/domain/form/service/FormService.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
Labels: 🚀 feature

#136 chore: 임시저장 예외케이스 수정
  layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
Labels: 👨‍💻 chore

#139 chore: 실행 목표 조회 로직 변경, 리뷰 사항 반영
  layer-api/src/main/java/org/layer/domain/actionItem/controller/ActionItemApi.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/ActionItemController.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/ActionItemCreateRequest.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/MemberActionItemElementResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/MemberActionItemGetResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/MemberActionItemResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/SpaceActionItemGetResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/SpaceRetrospectActionItemGetResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/service/ActionItemService.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
  layer-domain/src/main/java/org/layer/domain/actionItem/entity/ActionItem.java
  layer-domain/src/main/java/org/layer/domain/actionItem/repository/ActionItemRepository.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepository.java
Labels: 👨‍💻 chore

#141 fix: 회원 정보 조회 응답 imageUrl 추가
  layer-api/src/main/java/org/layer/domain/auth/controller/AuthApi.java
  layer-api/src/main/java/org/layer/domain/auth/controller/dto/MemberInfoResponse.java
Labels: 👨‍💻 chore

#144 fix: 로그인, 회원가입 응답 데이터에 이미지 url 추가
  layer-api/src/main/java/org/layer/domain/auth/controller/AuthApi.java
  layer-api/src/main/java/org/layer/domain/auth/controller/AuthController.java
  layer-api/src/main/java/org/layer/domain/auth/controller/dto/SignInResponse.java
  layer-api/src/main/java/org/layer/domain/auth/controller/dto/SignUpResponse.java
  layer-api/src/main/java/org/layer/domain/auth/service/AuthService.java
  layer-api/src/main/java/org/layer/domain/auth/service/dto/SignUpServiceResponse.java
Labels: 👨‍💻 chore

#146 fix: 스페이스 정렬 순서 변경하기
  layer-api/src/main/java/org/layer/domain/space/controller/dto/SpaceResponse.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepositoryImpl.java
Labels: 🛠️ enhancement

#145 Fix: 실행 목표 생성, 조회, 삭제 API 수정 & 실행 목표 편집 API 추가
  layer-api/src/main/java/org/layer/domain/actionItem/controller/ActionItemApi.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/ActionItemController.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/ActionItemResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/MemberActionItemResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/request/ActionItemCreateRequest.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/request/ActionItemUpdateRequest.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/response/MemberActionItemGetResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/response/RetrospectActionItemResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/response/SpaceActionItemElementResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/response/SpaceActionItemGetResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/response/SpaceRetrospectActionItemGetResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/service/ActionItemService.java
  layer-common/src/main/java/org/layer/common/exception/ActionItemExceptionType.java
  layer-domain/src/main/java/org/layer/domain/actionItem/dto/ActionItemResponse.java
  layer-domain/src/main/java/org/layer/domain/actionItem/dto/MemberActionItemResponse.java
  layer-domain/src/main/java/org/layer/domain/actionItem/entity/ActionItem.java
  layer-domain/src/main/java/org/layer/domain/actionItem/repository/ActionItemRepository.java
  layer-domain/src/main/java/org/layer/domain/retrospect/repository/RetrospectRepository.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepository.java
Labels: 🐞bug, 🚀 feature

#148 feat: 스페이스 단건조회 리더 아이디 반환하기
  layer-api/src/main/java/org/layer/domain/space/controller/dto/SpaceResponse.java
Labels: 🛠️ enhancement, 🚀 feature

#156 fix: 스페이스 떠나기 팀장확인 로직 변경
  layer-api/src/main/java/org/layer/domain/space/service/SpaceService.java
Labels: 🐞bug

#158 fix: 스페이스 조회시 리더 정보 응답하기 #157
  layer-api/src/main/java/org/layer/domain/space/controller/dto/SpaceResponse.java
  layer-domain/src/main/java/org/layer/domain/space/dto/Leader.java
  layer-domain/src/main/java/org/layer/domain/space/dto/SpaceWithMemberCount.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepositoryImpl.java
Labels: 🛠️ enhancement, 🚀 feature

#162 bug: 테이블 이름 변경
  layer-domain/src/main/java/org/layer/domain/analyze/entity/Analyze.java
Labels: 🐞bug

#164 chore: 추천 템플릿 조회 API 및 회고 수정 API 변경
  layer-api/src/main/java/org/layer/domain/form/controller/dto/request/RecommendFormQueryDto.java
  layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
Labels: 🐞bug, 👨‍💻 chore

#166 chore: fe 요청에 맞게 수정
  layer-api/src/main/java/org/layer/domain/answer/controller/dto/response/AnswerListGetResponse.java
  layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
  layer-api/src/main/java/org/layer/domain/form/service/FormService.java
  layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/response/RetrospectGetResponse.java
Labels: 👨‍💻 chore

#171 Chore/170: 실행목표 조회 API 응답 수정
  layer-api/src/main/java/org/layer/domain/actionItem/controller/dto/response/RetrospectActionItemResponse.java
  layer-api/src/main/java/org/layer/domain/actionItem/service/ActionItemService.java
  layer-domain/src/main/java/org/layer/domain/actionItem/dto/MemberActionItemResponse.java
Labels: 👨‍💻 chore

#173 chore: 스페이스 단건 조회 formTag 추가
  layer-api/src/main/java/org/layer/domain/space/controller/dto/SpaceResponse.java
  layer-domain/src/main/java/org/layer/domain/space/dto/SpaceWithMemberCount.java
  layer-domain/src/main/java/org/layer/domain/space/repository/SpaceRepositoryImpl.java
Labels: 👨‍💻 chore

#177 chore: 회고 생성 API 수정
  layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
Labels: 👨‍💻 chore

#180 fix: 질문에 대한 답변 추출 로직 수정
  layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
  layer-domain/src/main/java/org/layer/domain/answer/entity/Answers.java
Labels: 🐞bug

#181 feat: 애플로그인
  build.gradle
  layer-api/src/main/java/org/layer/LayerApplication.java
  layer-api/src/main/java/org/layer/config/SecurityConfig.java
  layer-api/src/main/java/org/layer/domain/auth/controller/AuthController.java
  layer-api/src/main/java/org/layer/domain/auth/service/AuthService.java
  layer-api/src/main/resources/application-dev.yml
  layer-api/src/main/resources/application-local.yml
  layer-api/src/main/resources/application-prod.yml
  layer-common/src/main/java/org/layer/common/exception/TokenExceptionType.java
  layer-domain/src/main/java/org/layer/domain/member/entity/SocialType.java
  layer-external/src/main/java/org/layer/oauth/config/AppleAuthClient.java
  layer-external/src/main/java/org/layer/oauth/dto/service/apple/ApplePublicKey.java
  layer-external/src/main/java/org/layer/oauth/dto/service/apple/ApplePublicKeyGenerator.java
  layer-external/src/main/java/org/layer/oauth/dto/service/apple/ApplePublicKeys.java
  layer-external/src/main/java/org/layer/oauth/dto/service/apple/AppleTokenParser.java
  layer-external/src/main/java/org/layer/oauth/exception/OAuthException.java
  layer-external/src/main/java/org/layer/oauth/service/apple/AppleService.java
Labels: 🚀 feature

#186 feat: 회고 마감 API 구현
  layer-api/src/main/java/org/layer/domain/retrospect/controller/RetrospectApi.java
  layer-api/src/main/java/org/layer/domain/retrospect/controller/RetrospectController.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
  layer-common/src/main/java/org/layer/common/exception/RetrospectExceptionType.java
  layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
  layer-domain/src/main/java/org/layer/domain/space/entity/Team.java
Labels: 🚀 feature

#188 fix: 회고 분석 팀원도 조회 가능하도록 변경
  layer-api/src/main/java/org/layer/domain/analyze/service/AnalyzeService.java
Labels: 🐞bug

#189 feat: 회고 마감 배치 작업 및 배포스크립트 수정
  .github/workflows/k3s.yaml
  build.gradle
  layer-batch/src/main/java/org/layer/BatchApplication.java
  layer-batch/src/main/java/org/layer/batch/scheduler/RetrospectScheduler.java
  layer-batch/src/main/resources/application.yml
  layer-domain/src/main/java/org/layer/domain/retrospect/repository/RetrospectCustomRepository.java
  layer-domain/src/main/java/org/layer/domain/retrospect/repository/RetrospectCustomRepositoryImpl.java
  layer-domain/src/main/java/org/layer/domain/retrospect/repository/RetrospectRepository.java
  settings.gradle
Labels: 🚀 feature, 📚 setting

#190 feat: 회고 분석 기능 전면 수정
  layer-api/src/main/java/org/layer/LayerApplication.java
  layer-api/src/main/java/org/layer/domain/analyze/controller/AnalyzeApi.java
  layer-api/src/main/java/org/layer/domain/analyze/controller/AnalyzeController.java
  layer-api/src/main/java/org/layer/domain/analyze/controller/dto/response/AnalyzeDetailResponse.java
  layer-api/src/main/java/org/layer/domain/analyze/controller/dto/response/AnalyzeGetResponse.java
  layer-api/src/main/java/org/layer/domain/analyze/controller/dto/response/AnalyzesGetResponse.java
  layer-api/src/main/java/org/layer/domain/analyze/service/AnalyzeService.java
  layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
  layer-domain/src/main/java/org/layer/domain/analyze/entity/Analyze.java
  layer-domain/src/main/java/org/layer/domain/analyze/entity/AnalyzeDetail.java
  layer-domain/src/main/java/org/layer/domain/analyze/enums/AnalyzeDetailType.java
  layer-domain/src/main/java/org/layer/domain/analyze/enums/AnalyzeType.java
  layer-domain/src/main/java/org/layer/domain/analyze/repository/AnalyzeRepository.java
  layer-domain/src/main/java/org/layer/domain/answer/entity/Answers.java
  layer-domain/src/main/java/org/layer/domain/answer/repository/AnswerRepository.java
  layer-domain/src/main/java/org/layer/domain/space/entity/Team.java
  layer-external/src/main/java/org/layer/external/ai/constant/OpenAIFactory.java
  layer-external/src/main/java/org/layer/external/ai/dto/request/Properties.java
  layer-external/src/main/java/org/layer/external/ai/dto/response/OpenAIResponse.java
Labels: 🚀 feature, 👨‍💻 chore

#192 chore: 개인 ai 분석 응답값 수정
  layer-api/src/main/java/org/layer/domain/analyze/controller/dto/response/AnalyzeIndividualGetResponse.java
  layer-api/src/main/java/org/layer/domain/analyze/controller/dto/response/AnalyzeTeamGetResponse.java
  layer-api/src/main/java/org/layer/domain/analyze/controller/dto/response/AnalyzesGetResponse.java
  layer-api/src/main/java/org/layer/domain/analyze/service/AnalyzeService.java
Labels: 👨‍💻 chore

#195 chore: 분석 로직 수정
  build.gradle
  layer-api/src/main/java/org/layer/domain/analyze/controller/AnalyzeController.java
  layer-api/src/main/java/org/layer/domain/analyze/service/AnalyzeService.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
  layer-batch/src/main/java/org/layer/batch/scheduler/RetrospectScheduler.java
  layer-domain/src/main/java/org/layer/domain/answer/entity/Answers.java
  layer-domain/src/main/java/org/layer/domain/retrospect/repository/RetrospectRepository.java
  layer-external/src/main/java/org/layer/external/ai/service/AIAnalyzeService.java
Labels: 👨‍💻 chore

#198 chore: formTag 생성 방식 변경
  layer-api/src/main/java/org/layer/domain/retrospect/controller/dto/request/RetrospectCreateRequest.java
  layer-api/src/main/java/org/layer/domain/retrospect/service/RetrospectService.java
Labels: 👨‍💻 chore

#201 feat: 내 분석 조회 API 구현
  layer-api/src/main/java/org/layer/domain/member/controller/MemberApi.java
  layer-api/src/main/java/org/layer/domain/member/controller/MemberController.java
  layer-api/src/main/java/org/layer/domain/member/controller/dto/GetMemberAnalyzesResponse.java
  layer-api/src/main/java/org/layer/domain/member/controller/dto/GetMemberRecentAnalyzeResponse.java
  layer-api/src/main/java/org/layer/domain/member/controller/dto/GetMemberRecentBadAnalyzeResponse.java
  layer-api/src/main/java/org/layer/domain/member/controller/dto/GetMemberRecentGoodAnalyzeResponse.java
  layer-api/src/main/java/org/layer/domain/member/controller/dto/GetMemberRecentImprovementAnalyzeResponse.java
  layer-api/src/main/java/org/layer/domain/member/service/MemberService.java
  layer-domain/src/main/java/org/layer/domain/analyze/entity/Analyze.java
  layer-domain/src/main/java/org/layer/domain/analyze/repository/AnalyzeRepository.java
  layer-domain/src/main/java/org/layer/domain/retrospect/dto/SpaceRetrospectDto.java
  layer-domain/src/main/java/org/layer/domain/retrospect/repository/RetrospectRepository.java
  layer-domain/src/main/java/org/layer/domain/space/repository/MemberSpaceRelationRepository.java
Labels: 🚀 feature
