Repository depromeet/layer-server, pull requests merged in 2025-03, with the labels that each got.

#294 fix: ai 분석 동시성 문제 해결
  build.gradle
  layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
  layer-common/src/main/java/org/layer/common/exception/RetrospectExceptionType.java
  layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
  layer-external/src/main/java/org/layer/external/ai/service/AIAnalyzeService.java
Labels: 🐞bug

#295 v1.1.3
  build.gradle
  layer-api/src/main/java/org/layer/domain/answer/service/AnswerService.java
  layer-common/src/main/java/org/layer/common/exception/RetrospectExceptionType.java
  layer-domain/src/main/java/org/layer/domain/retrospect/entity/Retrospect.java
  layer-external/src/main/java/org/layer/external/ai/service/AIAnalyzeService.java
Labels: deployment

#296 hotfix: redis expose port 제거
  .github/workflows/aws-cicd-dev.yml
  .github/workflows/aws-cicd-prod.yml
  layer-api/infra/development/docker-compose-blue.yaml
  layer-api/infra/development/docker-compose-green.yaml
  layer-api/infra/production/docker-compose-blue.yaml
  layer-api/infra/production/docker-compose-green.yaml
Labels: hotfix

#297 hotfix: docker-compose > redis port 제거
  .github/workflows/aws-cicd-dev.yml
  .github/workflows/aws-cicd-prod.yml
  layer-api/infra/development/docker-compose-blue.yaml
  layer-api/infra/development/docker-compose-green.yaml
  layer-api/infra/production/docker-compose-blue.yaml
  layer-api/infra/production/docker-compose-green.yaml
Labels: hotfix
